services:
  dev:
      container_name: evostats-dev
      build:
        context: .
        dockerfile: Dockerfile
        target: build
      ports:
        - "8080:8080"
      volumes:
        - .:/app
      networks:
        - evostat
      env_file:
        - .env
  evostats:
      container_name: evostats
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
        - evostat
      env_file:
        - .env

networks:
  evostat:
    driver: bridge